name: self-check
services:
- name: checker
  envs:
  - key: PUBLIC_URL
    value: "${PUBLIC_URL}"
    scope: RUN_TIME
  - key: PRIVATE_DOMAIN
    value: "${PRIVATE_DOMAIN}"
    scope: RUN_TIME
  http_port: 80
  routes:
  - path: /
  image:
    registry_type: DOCKER_HUB
    registry: jcodybaker
    repository: apps-self-check
    tag: latest